Repository laminas/laminas-db, pull requests merged in 2021-02, with the labels that each got.

#183 Switch to Laminas CI workflow for GHA
  .ci/mysql_fixtures_travis.sh
  .github/workflows/continuous-integration.yml
  .github/workflows/docs-build.yml
  .github/workflows/release-on-milestone-closed.yml
  .laminas-ci.json
  .laminas-ci/mysql_permissions.sql
  .laminas-ci/phpunit.xml
  .laminas-ci/pre-run.sh
  .travis.yml
  test/integration/Adapter/Driver/Mysqli/TraitSetup.php
  test/integration/IntegrationTestListener.php
  test/integration/Platform/MysqlFixtureLoader.php
Labels: Enhancement, Work In Progress

#148 Fix __METHOD__ inside closure (it is '{closure}')
  src/Adapter/Driver/Pgsql/Connection.php
  test/unit/Adapter/Driver/Pgsql/ConnectionTest.php
Labels: Bug

#149 Remove impossible check for array === null
  src/Sql/Update.php
Labels: Enhancement

#168 Adding documentation on usage of laminas db in mvc application
  docs/book/application-integration/usage-in-a-laminas-mvc-application.md
  mkdocs.yml
Labels: Documentation

#169 Fix MySQLi SSL flags handling to explicitly set MYSQLI_CLIENT_SSL if …
  src/Adapter/Driver/Mysqli/Connection.php
  test/unit/Adapter/Driver/Mysqli/ConnectionTest.php
Labels: Bug

#171 Fixes #23 : add Expression to docblock at Sql\Predicate\Predicate methods
  src/Sql/Predicate/Predicate.php
Labels: Documentation

#185 Fix issues with invalid parameter counts
  src/Adapter/ParameterContainer.php
  test/integration/Adapter/Driver/Pdo/Mysql/QueryTest.php
  test/unit/Adapter/ParameterContainerTest.php
Labels: Bug, Enhancement

#172 Fixes #22 add JOIN_FULL_OUTER for full outer join
  docs/book/sql.md
  src/Sql/Join.php
  src/Sql/Select.php
  test/unit/Sql/JoinTest.php
  test/unit/Sql/SelectTest.php
Labels: Enhancement

#184 Remove Float class
  phpunit.xml.dist
  src/Sql/Ddl/Column/Float.php
Labels: Bug, Feature Removal

#161 remove wrong driver/platform-name combination from oracle-platform
  src/Adapter/Platform/Oracle.php
  test/unit/Adapter/AdapterTest.php
Labels: Bug

#163 Adds delegator for AdapterAwareInterface
  composer.json
  composer.lock
  docs/book/adapters/adapter-aware-trait.md
  mkdocs.yml
  src/Adapter/AdapterServiceDelegator.php
  test/unit/Adapter/AdapterServiceDelegatorTest.php
  test/unit/Adapter/TestAsset/ConcreteAdapterAwareObject.php
Labels: Enhancement

#162 add resultPrototype getter for inspection
  src/Adapter/Driver/IbmDb2/IbmDb2.php
  src/Adapter/Driver/Pdo/Pdo.php
  src/Adapter/Driver/Pgsql/Pgsql.php
  src/Adapter/Driver/Sqlsrv/Sqlsrv.php
  test/unit/Adapter/Driver/IbmDb2/IbmDb2Test.php
  test/unit/Adapter/Driver/Pdo/PdoTest.php
  test/unit/Adapter/Driver/Pgsql/PgsqlTest.php
  test/unit/Adapter/Driver/Sqlsrv/SqlsrvTest.php
Labels: Enhancement

#182 Added MS SQL server that can be used to better test the integration.
  .ci/sqlsrv_install_drivers.sh
  .github/workflows/continuous-integration.yml
  .laminas-ci.json
  .laminas-ci/phpunit.xml
  test/integration/Adapter/Platform/SqlServerTest.php
  test/integration/IntegrationTestListener.php
  test/integration/Platform/SqlServerFixtureLoader.php
  test/integration/TestFixtures/mysql.sql
  test/integration/TestFixtures/sqlsrv-triggers.sql
  test/integration/TestFixtures/sqlsrv-views.sql
  test/integration/TestFixtures/sqlsrv.sql
  test/unit/Adapter/Driver/Sqlsrv/AbstractIntegrationTest.php
  test/unit/Adapter/Driver/Sqlsrv/ConnectionIntegrationTest.php
  test/unit/Adapter/Driver/Sqlsrv/PdoSqlSrvIntegrationTest.php
Labels: Enhancement
